version: '2.1'
services:
  resin-route:
    build: ./resin-route
    network_mode: host
    privileged: true
    restart: always
  wifi-connect:
    build: ./wifi-connect
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
    network_mode: host
    privileged: true
    restart: always
